### PR TITLE
New contributions

### PR DESCRIPTION
**Pull request by dcbr**
## What?
Fixes failing tests and lint checks.

## Why?
As this project is the most active fork of [Hopding/pdf-lib](https://github.com/Hopding/pdf-lib), I wondered if you would accept new contributions here? I'm mostly interested in extensions for PDF signing.
To start developing from a fresh clone of this repository, the changes in this PR were necessary to correctly run all tests and lint checks.

## How?
Mostly using `yarn upgrade`, `yarn add` and `yarn lint` commands, plus some manual fixes.

## Testing?
All tests run correctly now

## New Dependencies?
No

## Screenshots
N/A

## Suggested Reading?
No

## Anything Else?
N/A

## Checklist
- [x] I read [CONTRIBUTING.md](https://github.com/Hopding/pdf-lib/blob/master/docs/CONTRIBUTING.md).
- [x] I read [MAINTAINERSHIP.md#pull-requests](https://github.com/Hopding/pdf-lib/blob/master/docs/MAINTAINERSHIP.md#pull-requests).
- [x] I added/updated unit tests for my changes.
- [x] I added/updated integration tests for my changes.
- [x] I [ran the integration tests](https://github.com/Hopding/pdf-lib/blob/master/docs/CONTRIBUTING.md#running-the-integration-tests).
- [x] I tested my changes in Node, Deno, and the browser.
- [x] I viewed documents produced with my changes in Adobe Acrobat, Foxit Reader, Firefox, and Chrome.
- [x] I added/updated doc comments for any new/modified public APIs.
- [x] My changes work for both **new** and **existing** PDF files.
- [x] I [ran the linter](https://github.com/Hopding/pdf-lib/blob/master/docs/CONTRIBUTING.md#running-the-linter) on my changes.

### CODE REVIEW

**Comment by Sharcoux** [comment]
Thanks for your contribution.

We're going to test that and merge.

**Comment by dcbr** [comment]
Ok awesome :) Glad to see there is some activity for this extremely useful library!
I also noticed this project still uses `tslint`, which has been [deprecated](https://github.com/palantir/tslint/issues/4534) for some years now. I tried to convert to `eslint`, but I am not a linter expert and this caused some non-trivial changes (for me). So if someone is more familiar with that matter, I think it would be a good follow-up change.

**Comment by Sharcoux** [comment]
Yes, we forked a project that was using a stack we're not so comfortable with. We'd like to slowly update it to a stack we know better.

**Comment by Sharcoux** [comment]
Released in 1.20.3
Sorry for the mess in the repo. Was my first time trying to use the conflict resolution tool built in github and that didn't go well ^^"
Thanks for your contribution. :heart:

**Comment by dcbr** [comment]
No problem, thanks for the quick release! 🚀

**Pull request merged**
