### PR TITLE
Add conversion method from PDFObjects to typescript literals

### PR DESCRIPTION
**Pull request by dcbr**
## What?
Add an extra method to `PDFContext` which converts `PDFObject` to its literal representation (i.e. the reverse operation of the `obj` method).

Example:
```ts
const literal = {
    Foo: [12, 3],
    Bar: true,
};
const obj = context.obj(literal);
const literal2 = context.getLiteral(obj);
console.log(literal2.Foo); // [12, 3]
console.log(literal2.Bar); // true
```

## Why?
Simplify working with PDFObjects by converting them to their literal representations (i.e. PDFDicts become objects, PDFArrays become arrays, etc.)

## How?
Extra method on the `PDFContext` class, which already implements the reverse operation (from literal to PDFObject).

## Testing?
Some existing tests are modified and one extra test is added.

## New Dependencies?
No

## Screenshots
N/A

## Suggested Reading?
No

## Anything Else?
No

## Checklist
- [x] I read [CONTRIBUTING.md](https://github.com/Hopding/pdf-lib/blob/master/docs/CONTRIBUTING.md).
- [x] I read [MAINTAINERSHIP.md#pull-requests](https://github.com/Hopding/pdf-lib/blob/master/docs/MAINTAINERSHIP.md#pull-requests).
- [x] I added/updated unit tests for my changes.
- [x] I added/updated integration tests for my changes.
- [x] I [ran the integration tests](https://github.com/Hopding/pdf-lib/blob/master/docs/CONTRIBUTING.md#running-the-integration-tests).
- [x] I tested my changes in Node, Deno, and the browser.
- [x] I viewed documents produced with my changes in Adobe Acrobat, Foxit Reader, Firefox, and Chrome.
- [x] I added/updated doc comments for any new/modified public APIs.
- [x] My changes work for both **new** and **existing** PDF files.
- [x] I [ran the linter](https://github.com/Hopding/pdf-lib/blob/master/docs/CONTRIBUTING.md#running-the-linter) on my changes.

### CODE REVIEW

**Comment by Sharcoux** [comment]
Hi,

Thanks for your contribution.

I'm not sure about the second parameter of the method. Can you elaborate on why we should expose that?

**Comment by dcbr** [comment]
The idea was that the base `getLiteral` method (with default second parameter) is as close to the reverse operation of the `obj` method as possible. This means `PDFRef`, `PDFStream` and `PDFString` are returned as is, as they do not have a "literal" representation in the `obj` function. For example, to create a `PDFDict` containing a `PDFRef` and `PDFString` you have to explicitly write
```ts
const obj = context.obj({
    Ref: PDFRef.of(12),
    String: PDFString.of('Dummy'),
});
```
The second parameter of the `getLiteral` method allows you to "extend" the literal conversion, by additionally converting `PDFRef` to its object number, `PDFString` to its string value and `PDFStream` to its dictionary's literal representation. These choices are a bit arbitrary though: maybe for certain applications it would be better to convert `PDFRef` to the generation number instead, or `PDFStream` to their contents; hence why these are optional.
Alternatively, we could allow to pass a custom 'converter' function for these types, but I didn't want to make it too complicated for now, as I think the current implementation already covers the most useful conversions.

**Comment by Sharcoux** [comment]
I'm sorry, it's still a bit confusing to me. Can you give me an example of how you would use this second parameter exactly? Can you show me the same example as this:

```
const literal = {
    Foo: [12, 3],
    Bar: true,
};
const obj = context.obj(literal);
const literal2 = context.getLiteral(obj);
console.log(literal2.Foo); // [12, 3]
console.log(literal2.Bar); // true
```

But with that second parameter being used?

**Comment by dcbr** [comment]
Suppose we have
```ts
const literal = {
    Bool: true,
    Ref: PDFRef.of(12),
    String: PDFString.of('Dummy'),
}
const obj = context.obj(literal);
```
Then, the default (without second parameter) returns
```ts
let literal2 = context.getLiteral(obj);
console.log(literal2.Bool); // true
console.log(literal2.Ref); // PDFRef2 { objectNumber: 12, generationNumber: 0, tag: "12 0 R" }
console.log(literal2.String); // PDFString2 { value: "Dummy" }
```
With the second parameter this can be extended as follows
```ts
literal2 = context.getLiteral(obj, {literalRef: true});
console.log(literal2.Bool); // true
console.log(literal2.Ref); // 12
console.log(literal2.String); // PDFString2 { value: "Dummy" }
```
and
```ts
literal2 = context.getLiteral(obj, {literalRef: true, literalString: true});
console.log(literal2.Bool); // true
console.log(literal2.Ref); // 12
console.log(literal2.String); // "Dummy"
```

**Comment by Sharcoux** [comment]
Released in 1.20.3
Thanks for your contribution !

**Pull request merged**
