### PR TITLE
fix: skip invalid_xref

### PR DESCRIPTION
**Pull request by brandnday**
## What?

This PR is to address issue in https://github.com/cantoo-scribe/pdf-lib/issues/64
It is found that there is no problem with the pdf document, but the xref section is corrupted.

## Why?

Our team use this library and found this issue when we upload pdf with invalid xref. Turns out this [issue](https://github.com/cantoo-scribe/pdf-lib/issues/64) raised before

## How?

It will precheck if the digits in xref object is valid, if it is not valid, it will just return the empty xref

## Testing?

Ran the test locally

## Checklist
- [x] I read [CONTRIBUTING.md](https://github.com/Hopding/pdf-lib/blob/master/docs/CONTRIBUTING.md).
- [x] I read [MAINTAINERSHIP.md#pull-requests](https://github.com/Hopding/pdf-lib/blob/master/docs/MAINTAINERSHIP.md#pull-requests).
- [x] I added/updated unit tests for my changes.
- [ ] I added/updated integration tests for my changes.
- [ ] I [ran the integration tests](https://github.com/Hopding/pdf-lib/blob/master/docs/CONTRIBUTING.md#running-the-integration-tests).
- [ ] I tested my changes in Node, Deno, and the browser.
- [ ] I viewed documents produced with my changes in Adobe Acrobat, Foxit Reader, Firefox, and Chrome.
- [x] I added/updated doc comments for any new/modified public APIs.
- [x] My changes work for both **new** and **existing** PDF files.
- [x] I [ran the linter](https://github.com/Hopding/pdf-lib/blob/master/docs/CONTRIBUTING.md#running-the-linter) on my changes.

### CODE REVIEW

**Comment by Sharcoux** [comment]
Your test case need to test a normal pdf and and corrupted one. You can manually corrupt a pdf existing in the repo if needed.

**Comment by brandnday** [comment]
@Sharcoux I included the corrupted file (`invalid_xref.pdf`) and use it for the new unit test. I corrupt the file by copy pasting the corrupted xref section from the pdf mentioned in the issue. I also tested the new test case without the fix and it reproduce the error reported in the issue.

image

**Comment by Sharcoux** [comment]
Merged. Will be released soon. Thanks :heart:

**Comment by Sharcoux** [comment]
Released

**Pull request merged**
